version: '3.8'

services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: always
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: redis://redis:6379/
      PUPPETEER_WS_ENDPOINT: ws://browserless:3000
      # 填入你的公网HTTPS域名
      DOMAIN: https://rss158.19996661.xyz
      # 改成你自己的强密钥
      ACCESS_KEY: wcb123456L0.
      CACHE_EXPIRE: 3600
    depends_on:
      - redis
      - browserless

  browserless:
    image: browserless/chrome
    container_name: rsshub-browser
    restart: always
    ulimits:
      core:
        hard: 0
        soft: 0

  redis:
    image: redis:alpine
    container_name: rsshub-redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: